services:
  n8n:
    container_name: n8n
    image: n8nio/n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${N8N_DOMAIN}
      - WEBHOOK_URL=https://${N8N_DOMAIN}/
      - WEBHOOK_TUNNEL_URL=https://${N8N_DOMAIN}/
      # Configuraci√≥n de Redis
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_DB=0
    volumes:
      - ./data:/home/node/.n8n
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

  postgres-vector:
    container_name: postgres-vector
    image: ankane/pgvector:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=set-user
      - POSTGRES_PASSWORD=set-any-password
      - POSTGRES_DB=set-any-database
    volumes:
      - ./postgres-vector-data:/var/lib/postgresql/data